### ISSUE TITLE
Docs: wrong linking

### ISSUE THREAD

**Issue by 0x6a6868** [karolsluszniak/phoenix_live_controller#1]
Hey, exciting project. Could you please create a `tag` for the current (and also next releases) so that the documentation at gets correctly linked to the source code.

e.g. https://github.com/karolsluszniak/phoenix_live_controller/blob/v0.1.0/lib/phoenix_live_controller.ex#L1 

Thanks!

**Comment by karolsluszniak** [comment]
Done, thanks for reporting!
